//
// Created by someusername on 5/28/20.
//

#ifndef STOCHASTIC_SYSTEM_MINIMIZATION_CARDELLIAGGREGATION_H
#define STOCHASTIC_SYSTEM_MINIMIZATION_CARDELLIAGGREGATION_H


class CardelliAggregation {

};


#endif //STOCHASTIC_SYSTEM_MINIMIZATION_CARDELLIAGGREGATION_H
