//
// Created by someusername on 5/28/20.
//

#ifndef STOCHASTIC_SYSTEM_MINIMIZATION_DIFFERENTIALEQUATION_H
#define STOCHASTIC_SYSTEM_MINIMIZATION_DIFFERENTIALEQUATION_H

class DifferentialEquation {};

#endif // STOCHASTIC_SYSTEM_MINIMIZATION_DIFFERENTIALEQUATION_H
