//
// Created by someusername on 5/28/20.
//

#ifndef STOCHASTIC_SYSTEM_MINIMIZATION_DIFFERENTIALEQUATIONINSTANCE_H
#define STOCHASTIC_SYSTEM_MINIMIZATION_DIFFERENTIALEQUATIONINSTANCE_H


class DifferentialEquationInstance {

};


#endif //STOCHASTIC_SYSTEM_MINIMIZATION_DIFFERENTIALEQUATIONINSTANCE_H
