//
// Created by someusername on 6/22/20.
//

#ifndef STOCHASTIC_SYSTEM_MINIMIZATION_DIFFERENTIALEQUATIONRULENETWORKCONVERSION_H
#define STOCHASTIC_SYSTEM_MINIMIZATION_DIFFERENTIALEQUATIONRULENETWORKCONVERSION_H

class DifferentialEquationRuleNetworkConversion {};

#endif // STOCHASTIC_SYSTEM_MINIMIZATION_DIFFERENTIALEQUATIONRULENETWORKCONVERSION_H
