//
// Created by someusername on 6/22/20.
//

#ifndef STOCHASTIC_SYSTEM_MINIMIZATION_WEIGHTEDAUTOMATONRULENETWORKCONVERSION_H
#define STOCHASTIC_SYSTEM_MINIMIZATION_WEIGHTEDAUTOMATONRULENETWORKCONVERSION_H

class WeightedAutomatonRuleNetworkConversion {};

#endif // STOCHASTIC_SYSTEM_MINIMIZATION_WEIGHTEDAUTOMATONRULENETWORKCONVERSION_H
